//! 编译脚本（Cargo build script）。
//!
//! 作用：
//! 1. 在编译期扫描 `mapping/**/*.yml`；
//! 2. 生成 `OUT_DIR/embedded_mappings.rs`；
//! 3. 产出 `EMBEDDED_FIELD_MAPPINGS` 静态索引供运行时加载器使用。
//!
//! 这样新增供应商时，只需新增 mapping 文件，不需要再手改 Rust 代码里的 `include_str!` 列表。

use std::{
    collections::HashMap,
    env, fs,
    io::{self, Write},
    path::{Path, PathBuf},
};

fn main() {
    // 这些文件/目录变化后，触发 build.rs 重新执行。
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=mapping");

    // 项目根目录（Cargo.toml 所在目录）。
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR should exist"));
    let mapping_root = manifest_dir.join("mapping");
    let mut files = Vec::new();

    // 递归收集所有 yml mapping 文件。
    if mapping_root.exists() {
        collect_mapping_files(&mapping_root, &mut files)
            .expect("failed to collect mapping files from mapping/");
    }

    // 以文件名（去掉扩展名）作为 provider key，要求全局唯一。
    let mut provider_paths: HashMap<String, PathBuf> = HashMap::new();
    for file in files {
        let provider = file
            .file_stem()
            .and_then(|name| name.to_str())
            .map(|name| name.to_ascii_lowercase())
            .expect("mapping filename should be valid UTF-8 and have a file stem");

        if let Some(existing) = provider_paths.insert(provider.clone(), file.clone()) {
            panic!(
                "duplicate embedded mapping provider '{}': '{}' and '{}'",
                provider,
                existing.display(),
                file.display()
            );
        }
    }

    // 生成稳定输出，避免无序 map 导致重复构建内容抖动。
    let mut providers = provider_paths.into_iter().collect::<Vec<_>>();
    providers.sort_by(|a, b| a.0.cmp(&b.0));

    // 生成 Rust 源码：`(&str provider, &str yaml_content)` 数组。
    let mut generated = String::new();
    generated.push_str("// @generated by build.rs. DO NOT EDIT.\n");
    generated.push_str("pub(super) static EMBEDDED_FIELD_MAPPINGS: &[(&str, &str)] = &[\n");
    for (provider, path) in providers {
        let path_literal = path.to_string_lossy().to_string();
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            provider, path_literal
        ));
    }
    generated.push_str("];\n");

    // 写入 OUT_DIR，供主代码通过 include! 引入。
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR should exist"));
    let output_path = out_dir.join("embedded_mappings.rs");
    let mut output =
        fs::File::create(&output_path).expect("failed to create generated mapping index");
    output
        .write_all(generated.as_bytes())
        .expect("failed to write generated mapping index");
}

/// 递归收集目录下所有 `.yml` 文件路径。
fn collect_mapping_files(dir: &Path, files: &mut Vec<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            collect_mapping_files(&path, files)?;
            continue;
        }

        let is_yaml = path
            .extension()
            .and_then(|ext| ext.to_str())
            .map(|ext| ext.eq_ignore_ascii_case("yml"))
            .unwrap_or(false);

        if is_yaml {
            files.push(path);
        }
    }

    Ok(())
}
