[package]
name = "beancount-importer-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = "1.33"
serde_yaml = "0.9.34"
regex = "1.12.2"
rust_decimal_macros = "1.40.0"
thiserror = "2.0.18"
once_cell = "1.21.3"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
log = "0.4.29"
env_logger = "0.11.8"
calamine = "0.26"

# Cargo.toml 中自定义 release profile
[profile.release]
opt-level = 3        # 优化级别 0-3，"s"（体积）或 "z"（极致压缩）
lto = true           # 开启链接时优化，进一步减小体积、提升性能
codegen-units = 1    # 单个代码生成单元，优化更彻底（编译变慢）
panic = "abort"      # panic 直接退出，不展开堆栈（减小体积）
strip = true         # 去除符号表，进一步缩小体积（Rust 1.59+）
